project_id = "xxdswrvqdzqtxbiamkqw"

[functions.invite-user]
verify_jwt = true

[functions.check-reminders]
verify_jwt = false

[functions.fb-conversions]
verify_jwt = false

[functions.asaas-checkout]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-subscription-actions]
verify_jwt = true
